# Generated by Django 5.0.13 on 2025-09-01 18:29

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import donors.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(help_text='9 ספרות ללא מקפים', max_length=9, unique=True, validators=[donors.models.validate_israeli_id], verbose_name='תעודת זהות')),
                ('first_name', models.CharField(max_length=100, verbose_name='שם פרטי')),
                ('last_name', models.CharField(max_length=100, verbose_name='שם משפחה')),
                ('date_of_birth', models.DateField(help_text='פורמט: YYYY-MM-DD', verbose_name='תאריך לידה')),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='סוג דם')),
                ('health_status', models.CharField(choices=[('excellent', ' מצויין'), ('good', 'טוב'), ('fair', 'סביר'), ('poor', 'לא טוב')], default='good', max_length=10, verbose_name='מצב בריאות')),
                ('phone_number', models.CharField(help_text='פורמט: 05X-XXXXXXX', max_length=15, unique=True, validators=[donors.models.validate_israeli_phone], verbose_name='טלפון')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='אימייל')),
                ('address', models.TextField(blank=True, null=True, verbose_name='כתובת')),
                ('smoking_status', models.CharField(choices=[('never', 'לא מעשן'), ('former', 'עישן בעבר'), ('light', 'מעשן קל (עד 5/יום)'), ('heavy', 'מעשן כבד (5+/יום)')], default='never', max_length=10, verbose_name='עישון')),
                ('alcohol_use', models.CharField(choices=[('never', 'לא שותה'), ('social', 'באירועים'), ('weekly', 'מספר פעמים בשבוע'), ('daily', 'יומי')], default='never', max_length=10, verbose_name='אלכוהול')),
                ('has_chronic_illness', models.BooleanField(default=False, verbose_name='חולה במחלות כרוניות')),
                ('chronic_illness_details', models.TextField(blank=True, help_text='פרט את סוג המחלות והטיפול', null=True, verbose_name='פרטי מחלות כרוניות')),
                ('last_medical_exam', models.DateField(blank=True, help_text='תאריך הבדיקה הרפואית האחרונה', null=True, verbose_name='תאריך בדיקה רפואית אחרונה')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='נוצר ב')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='עודכן ב')),
                ('user', models.OneToOneField(blank=True, help_text='מקושר לחשבון משתמש (אופציונלי)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donor', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'תורם',
                'verbose_name_plural': 'תורמים',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_date', models.DateField(default=datetime.date.today, verbose_name='תאריך תרומה')),
                ('volume_ml', models.PositiveSmallIntegerField(default=450, help_text='נפח תרומה סטנדרטי: 450 מ"ל', validators=[django.core.validators.MinValueValidator(350), django.core.validators.MaxValueValidator(500)], verbose_name='נפח (מ"ל)')),
                ('notes', models.TextField(blank=True, help_text='הערות נוספות על התרומה', verbose_name='הערות')),
                ('is_approved', models.BooleanField(default=True, help_text='האם התרומה אושרה על ידי הרופא', verbose_name='אושר')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations_created', to=settings.AUTH_USER_MODEL, verbose_name='נוצר על ידי')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='donors.donor', verbose_name='תורם')),
            ],
            options={
                'verbose_name': 'תרומת דם',
                'verbose_name_plural': 'תרומות דם',
                'ordering': ['-donation_date'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient')], max_length=10, verbose_name='Role')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^(\\+972|0)(\\-)?5[02-9](\\-)?\\d{7}$', 'מספר טלפון לא תקין')], verbose_name='Phone Number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('normal', 'בקשה רגילה'), ('urgent', 'דחוף'), ('critical', 'מצב קריטי (חירום)')], default='normal', max_length=10, verbose_name='דחיפות')),
                ('patient_name', models.CharField(max_length=120, verbose_name='שם המטופל')),
                ('blood_type_needed', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='סוג דם נדרש')),
                ('units_needed', models.PositiveIntegerField(help_text='מקסימום 10 יחידות לבקשה', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='יחידות נדרשות')),
                ('emergency', models.BooleanField(default=False, help_text='סימון זה יגרום לשינוי סוג הדם ל-O- אוטומטית', verbose_name='בקשה דחופה?')),
                ('date_requested', models.DateTimeField(default=django.utils.timezone.now, verbose_name='תאריך בקשה')),
                ('fulfilled', models.BooleanField(default=False, verbose_name='מולא?')),
                ('fulfilled_date', models.DateTimeField(blank=True, null=True, verbose_name='תאריך מילוי')),
                ('notes', models.TextField(blank=True, help_text='הערות נוספות על הבקשה', verbose_name='הערות')),
                ('requested_by', models.ForeignKey(help_text='המשתמש שביצע את הבקשה', on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to=settings.AUTH_USER_MODEL, verbose_name='מבקש')),
            ],
            options={
                'verbose_name': 'בקשת דם',
                'verbose_name_plural': 'בקשות דם',
                'ordering': ['-date_requested'],
                'indexes': [models.Index(fields=['priority', 'fulfilled'], name='donors_bloo_priorit_3c258d_idx'), models.Index(fields=['blood_type_needed'], name='donors_bloo_blood_t_23865e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['blood_type'], name='donors_dono_blood_t_f4204f_idx'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['national_id'], name='donors_dono_nationa_90af50_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['donation_date'], name='donors_dona_donatio_404da8_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['is_approved'], name='donors_dona_is_appr_6c27ee_idx'),
        ),
    ]
