# Generated by Django 5.0.13 on 2025-08-15 08:32

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('normal', 'בקשה רגילה'), ('urgent', 'דחוף'), ('critical', 'מצב קריטי (חירום)')], default='normal', max_length=10, verbose_name='דחיפות')),
                ('patient_name', models.CharField(max_length=120, verbose_name='שם המטופל')),
                ('blood_type_needed', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='סוג דם נדרש')),
                ('units_needed', models.PositiveIntegerField(help_text='מקסימום 10 יחידות לבקשה', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='יחידות נדרשות')),
                ('emergency', models.BooleanField(default=False, verbose_name='בקשה דחופה?')),
                ('date_requested', models.DateTimeField(default=django.utils.timezone.now, verbose_name='תאריך בקשה')),
                ('fulfilled', models.BooleanField(default=False, verbose_name='מולא?')),
            ],
            options={
                'verbose_name': 'בקשת דם',
                'verbose_name_plural': 'בקשות דם',
                'ordering': ['-date_requested'],
            },
        ),
        migrations.AlterModelOptions(
            name='donor',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'תורם', 'verbose_name_plural': 'תורמים'},
        ),
        migrations.RemoveField(
            model_name='donor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='healthy',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='last_donation',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='medical_notes',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='total_units_donated',
        ),
        migrations.AddField(
            model_name='donor',
            name='alcohol_use',
            field=models.CharField(choices=[('never', 'לא שותה'), ('social', 'באירועים'), ('weekly', 'מספר פעמים בשבוע'), ('daily', 'יומי')], default='never', max_length=10, verbose_name='אלכוהול'),
        ),
        migrations.AddField(
            model_name='donor',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='donor',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='פורמט: YYYY-MM-DD', null=True, verbose_name='תאריך לידה'),
        ),
        migrations.AddField(
            model_name='donor',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='שם פרטי'),
        ),
        migrations.AddField(
            model_name='donor',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='פעיל במערכת'),
        ),
        migrations.AddField(
            model_name='donor',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='שם משפחה'),
        ),
        migrations.AddField(
            model_name='donor',
            name='smoking_status',
            field=models.CharField(choices=[('never', 'לא מעשן'), ('former', 'עישן בעבר'), ('light', 'מעשן קל (עד 5/יום)'), ('heavy', 'מעשן כבד (5+/יום)')], default='never', max_length=10, verbose_name='עישון'),
        ),
        migrations.AddField(
            model_name='donor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True, verbose_name='סוג דם'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='national_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='תעודת זהות'),
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_date', models.DateField(default=datetime.date.today, verbose_name='תאריך תרומה')),
                ('volume_ml', models.PositiveSmallIntegerField(default=450, validators=[django.core.validators.MinValueValidator(350), django.core.validators.MaxValueValidator(500)], verbose_name='נפח (מ"ל)')),
                ('notes', models.TextField(blank=True, verbose_name='הערות')),
                ('is_approved', models.BooleanField(default=True, verbose_name='אושר')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='donors.donor', verbose_name='תורם')),
            ],
            options={
                'verbose_name': 'תרומת דם',
                'verbose_name_plural': 'תרומות דם',
                'ordering': ['-donation_date'],
            },
        ),
    ]
