# Generated by Django 5.0.13 on 2025-09-03 06:02

import donors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='national_id',
            field=models.CharField(blank=True, help_text='9 digits without dashes', max_length=9, null=True, validators=[donors.models.validate_israeli_id], verbose_name='National ID'),
        ),
    ]
