# Generated by Django 5.0.13 on 2025-08-15 10:57

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_bloodrequest_alter_donor_options_remove_donor_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='donor_id',
            field=models.CharField(blank=True, help_text='מספר מזהה ייחודי של התורם במערכת', max_length=20, null=True, unique=True, verbose_name='מספר תורם'),
        ),
        migrations.AddField(
            model_name='donor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='אימייל'),
        ),
        migrations.AddField(
            model_name='donor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="מספר טלפון חייב להיות בפורמט: '+972501234567'", regex='^\\+?972\\d{9}$')], verbose_name='טלפון'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='נוצר בתאריך'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='שם פרטי'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='שם משפחה'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='national_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{9}$', 'תעודת זהות חייבת להכיל 9 ספרות')], verbose_name='תעודת זהות'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='עודכן בתאריך'),
        ),
    ]
