# Generated by Django 5.0.13 on 2025-10-26 15:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_profile_national_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='last_medical_exam',
            field=models.DateField(blank=True, help_text='תאריך הבדיקה הרפואית האחרונה - לא יכול להיות בעתיד', null=True, verbose_name='תאריך בדיקה רפואית אחרונה'),
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('doctor', 'Doctor Report'), ('patient', 'Patient Report')], max_length=20, verbose_name='Report Type')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Generated At')),
                ('pdf_file', models.FileField(upload_to='user_reports/%Y/%m/%d/', verbose_name='PDF File')),
                ('email_sent', models.BooleanField(default=False, verbose_name='Email Sent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Report',
                'verbose_name_plural': 'User Reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_needed', models.PositiveIntegerField(help_text='מקסימום 20 יחידות לבקשת חירום', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='יחידות נדרשות')),
                ('contact_name', models.CharField(help_text='שם האדם המבקש את תרומת הדם', max_length=120, verbose_name='שם איש קשר')),
                ('contact_phone', models.CharField(help_text='מספר טלפון להתקשרות דחופה', max_length=15, verbose_name='טלפון איש קשר')),
                ('contact_relationship', models.CharField(choices=[('family', 'בן משפחה'), ('friend', 'חבר/מכר'), ('medical_staff', 'צוות רפואי'), ('other', 'אחר')], default='family', max_length=100, verbose_name='קשר למטופל')),
                ('patient_name', models.CharField(blank=True, help_text='שם המטופל הזקוק לדם', max_length=120, verbose_name='שם המטופל (אם רלוונטי)')),
                ('hospital', models.CharField(help_text='מיקום המטופל', max_length=200, verbose_name='בית חולים/מיקום')),
                ('blood_type_needed', models.CharField(default='O-', editable=False, max_length=3, verbose_name='סוג דם נדרש')),
                ('date_requested', models.DateTimeField(default=django.utils.timezone.now, verbose_name='תאריך וזמן הבקשה')),
                ('fulfilled', models.BooleanField(default=False, verbose_name='סופק?')),
                ('fulfilled_date', models.DateTimeField(blank=True, null=True, verbose_name='תאריך סיפוק')),
                ('emergency_level', models.CharField(choices=[('critical', 'מצב קריטי'), ('urgent', 'דחוף'), ('stable', 'יציב אך דורש דם')], default='critical', max_length=20, verbose_name='רמת חירום')),
                ('automatic_match', models.BooleanField(default=True, help_text='המערכת תאתר אוטומטית תורמי O-', verbose_name='התאמה אוטומטית')),
                ('notes', models.TextField(blank=True, help_text='פרטים נוספים על המצב (רשות)', verbose_name='הערות נוספות')),
                ('matched_donors', models.ManyToManyField(blank=True, help_text='תורמי O- שהותאמו אוטומטית', to='donors.donor', verbose_name='תורמים מותאמים')),
            ],
            options={
                'verbose_name': 'בקשת חירום',
                'verbose_name_plural': 'בקשות חירום',
                'ordering': ['-date_requested'],
                'indexes': [models.Index(fields=['fulfilled', 'date_requested'], name='donors_emer_fulfill_d94e05_idx'), models.Index(fields=['emergency_level'], name='donors_emer_emergen_255579_idx')],
            },
        ),
    ]
