# Generated by Django 5.0.13 on 2025-08-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0003_donor_donor_id_donor_email_donor_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='שם פרטי'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='שם משפחה'),
        ),
    ]
