# Generated by Django 5.0.13 on 2025-10-26 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0003_alter_donor_last_medical_exam_userreport_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_he', models.CharField(help_text='שם היישוב בעברית', max_length=100, unique=True, verbose_name='שם היישוב (עברית)')),
                ('name_en', models.CharField(help_text='שם היישוב באנגלית', max_length=100, unique=True, verbose_name='שם היישוב (אנגלית)')),
                ('city_type', models.CharField(choices=[('city', 'עיר'), ('local_council', 'מועצה מקומית'), ('regional_council', 'מועצה אזורית'), ('kibbutz', 'קיבוץ'), ('moshav', 'מושב'), ('village', 'כפר')], max_length=20, verbose_name='סוג יישוב')),
                ('district', models.CharField(choices=[('jerusalem', 'מחוז ירושלים'), ('north', 'מחוז הצפון'), ('haifa', 'מחוז חיפה'), ('center', 'מחוז המרכז'), ('tel_aviv', 'מחוז תל אביב'), ('south', 'מחוז הדרום'), ('judea_samaria', 'מחוז יהודה ושומרון')], max_length=20, verbose_name='מחוז')),
                ('latitude', models.DecimalField(decimal_places=6, help_text='קו רוחב גיאוגרפי', max_digits=9, verbose_name='קו רוחב')),
                ('longitude', models.DecimalField(decimal_places=6, help_text='קו אורך גיאוגרפי', max_digits=9, verbose_name='קו אורך')),
                ('has_hospital', models.BooleanField(default=False, help_text='האם יש ביישוב בית חולים', verbose_name='קיים בית חולים')),
                ('has_blood_bank', models.BooleanField(default=False, help_text='האם יש ביישוב בנק דם', verbose_name='קיים בנק דם')),
            ],
            options={
                'verbose_name': 'יישוב',
                'verbose_name_plural': 'יישובים',
                'ordering': ['name_he'],
            },
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='נוצר ב')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='עודכן ב')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_locations', to='donors.location', verbose_name='יישוב')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_location', to=settings.AUTH_USER_MODEL, verbose_name='משתמש')),
            ],
            options={
                'verbose_name': 'מיקום משתמש',
                'verbose_name_plural': 'מיקומי משתמשים',
            },
        ),
    ]
