# Generated by Django 5.0.13 on 2025-08-15 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0004_alter_donor_first_name_alter_donor_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='donor_id',
        ),
    ]
