# Generated by Django 5.0.13 on 2025-08-15 17:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0005_remove_donor_donor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='donor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="מספר טלפון חייב להיות בפורמט: '+972501234567'", regex='^\\+?0\\d{9}$')], verbose_name='טלפון'),
        ),
    ]
